name: Build

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish FunctionApp
        run: dotnet publish -c Release -r win-x64 --output publish
        working-directory: SampleFunctionApp

      - name: Upload FunctionApp
        uses: actions/upload-artifact@v3
        with:
          name: functionapp
          path: ${{ github.workspace }}/SampleFunctionApp/publish/

      - name: Upload IaC
        uses: actions/upload-artifact@v3
        with:
          name: iac
          path: ${{ github.workspace }}/IaC
