name: Build

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish FunctionApp
        run: dotnet publish --configuration Release --os win --output publish
        working-directory: SampleFunctionApp

      - name: Upload FunctionApp
        uses: actions/upload-artifact@v1
        with:
          name: sample-function-app
          path: ${{ github.workspace }}/SampleFunctionApp/publish/

      - name: Upload IaC
        uses: actions/upload-artifact@v1
        with:
          name: iac
          path: ${{ github.workspace }}/IaC
