name: Build

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - shell: pwsh
        run: |
          cd SampleFunctionApp
          dotnet publish --configuration Release --os win --output publish
          Compress-Archive -Path ${{ github.workspace }}/SampleFunctionApp/publish/* -DestinationPath ${{ github.workspace }}/sample-function-app.zip

      - uses: actions/upload-artifact@v1
        with:
          name: sample-function-app
          path: ${{ github.workspace }}/sample-function-app.zip
