name: Build

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          cd SampleFunctionApp
          dotnet restore
          dotnet publish --configuration Release --output publish

      - uses: vimtor/action-zip@v1
        with:
          files: ${{ github.workspace }}/SampleFunctionApp/publish/
          dest: sample-function-app.zip

      - uses: actions/upload-artifact@v1
        with:
          name: sample-function-app
          path: ${{ github.workspace }}/sample-function-app.zip
